name: Deploy on Merge

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci
        
      - name: Set Git identity
        run: |
          git config user.email "manas.a.shinde11@gmail.com"
          git config user.name "manas-shinde"

      - name: Run deploy command
        run: npm run deploy
        env:
          NODE_ENV: production
